### ISSUE TITLE
Always shows Waiting for database to be ready

### ISSUE THREAD

**Issue by dheeth** [emilpriver/geni#162]
Not sure what's the issue here but I am not able to run migrations for postgres.

is it because user of my postgres instance is `postgres` itself?

There is no mode to see verbose or debug

export DATABASE_URL="postgres://postgres:migrate@migrations-test:5432/orchestrator?sslmode=disable"

I am trying to do it in my test setup of docker containers

**Comment by dheeth** [comment]
I installed postgresql-client from the container I am trying to run the command and it says the postgresql url is accessible and able to connect to database

**Comment by dheeth** [comment]
Sometimes I get the error - [ERROR] error returned from database: syntax error at or near "-"

I tried changing the name of postgres host from migrations-test to mydb by adding entry in /etc/hosts but then it again gets stuck on Waiting for database to be ready

**Comment by emilpriver** [comment]
Hey, 
`Waiting for database to be ready` eccentially means that either the database is not up and running or the connection string is wrong.

Can you provide me with more information on how you run Geni? Is the docker container a standalone docker container and your running it from your computer? If so should the host be `localhost` 

``` 
export DATABASE_URL="postgres://postgres:migrate@localhost:5432/orchestrator?sslmode=disable"
```

Dubbel check if the connection information is correct

**Comment by dheeth** [comment]
I have postgres in one container and then geni in another but both the containers are in same network and psql is able to connect to it from the container in which geni is running

**Comment by dheeth** [comment]
Verified the same connection information is working with other tools as expected

**Comment by emilpriver** [comment]
I am not able to help if I don't get more information.
I am using geni and postgres in a docker container without any issues and this is my docker-compose file:

```
version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
  migration-postgres:
    image: ghcr.io/emilpriver/geni:v1.0.11
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./postgres/migrations:/migrations
    command: up
```

I think you need to dubbel check that your setup is correct
